# The Analysis of the Diagonal Symmetry of the OD Matrix



$$
SI = \frac{\sum_{i=1}^{n} \sum_{j=1}^{n} \left| OD_{ij} - OD_{ji} \right|}{\sum_{i=1}^{n} \sum_{j=1}^{n} (OD_{ij} + OD_{ji})}
$$

In [6]:
import numpy as np
import pandas as pd
from scipy.stats import ttest_rel, wilcoxon
import seaborn as sns
import matplotlib.pyplot as plt

read int the TTM:

In [7]:
r5TTM = pd.read_csv(r'/mnt/d/University College London/Chen, Huanfa - Dissertation_Mengyu_Ding/Data/greater_london_od_mat_all/ttm_r5py_nan_handled.csv', encoding='latin1')

hereTTM = pd.read_csv(r'/mnt/d/University College London/Chen, Huanfa - Dissertation_Mengyu_Ding/Data/greater_london_od_mat_all/here_routing_matrix_format.csv', encoding='latin1')
# osrm not in mattrix format yet!
osrm_TTM = pd.read_csv(r'/mnt/d/University College London/Chen, Huanfa - Dissertation_Mengyu_Ding/Data/greater_london_od_mat_all/osrmTTM.csv', encoding='latin1')

val_TTM = pd.read_csv(r'/mnt/d/University College London/Chen, Huanfa - Dissertation_Mengyu_Ding/Data/ttm_valhalla.csv', encoding='latin1')
#val_TTM.set_index('originID', inplace=True)
# make the first column the index:
r5TTM.set_index('originID', inplace=True)
hereTTM.set_index('originID', inplace=True)
osrm_TTM.set_index('origin_msoaID', inplace=True)
val_TTM.set_index('originID', inplace=True)
# times 60 for all elements in the matrix
r5TTM = r5TTM * 60

In [3]:
r5TTM.head()

,E02000001,E02000002,E02000003,E02000004,E02000005,E02000007,E02000008,E02000009,E02000010,E02000011,...,E02007083,E02007084,E02007108,E02007109,E02007110,E02007111,E02007112,E02007113,E02007114,E02007115
originID,,,,,,,,,,,,,,,,,,,,,
E02000001,0.0,2220.0,2040.0,2100.0,1920.0,1980.0,1800.0,1740.0,1800.0,1980.0,...,1320.0,1380.0,720.0,720.0,540.0,420.0,1140.0,1140.0,1200.0,600.0
E02000002,2220.0,0.0,540.0,780.0,720.0,840.0,780.0,720.0,960.0,1020.0,...,3060.0,3120.0,1740.0,1860.0,2040.0,2040.0,1560.0,1560.0,1620.0,2580.0
E02000003,1980.0,300.0,0.0,540.0,240.0,360.0,360.0,360.0,480.0,540.0,...,2760.0,2880.0,1560.0,1680.0,1860.0,1860.0,1260.0,1260.0,1320.0,2460.0
E02000004,2100.0,900.0,540.0,0.0,480.0,300.0,480.0,540.0,420.0,420.0,...,2940.0,3000.0,2040.0,2160.0,2340.0,2280.0,1440.0,1440.0,1500.0,2700.0
E02000005,1860.0,600.0,240.0,420.0,0.0,240.0,180.0,300.0,300.0,420.0,...,2700.0,2760.0,1800.0,1920.0,2100.0,2040.0,1200.0,1140.0,1260.0,2460.0

In [4]:
def calculate_si_from_dataframe(df):
    """
    Calculate the Symmetry Index (SI) for an OD matrix represented as a DataFrame.

    Parameters:
    df (pd.DataFrame): A square OD matrix with row and column labels.

    Returns:
    float: The Symmetry Index (SI).
    """
    od_matrix = df.values
    od_transpose = od_matrix.T
    abs_diff = np.abs(od_matrix - od_transpose)
    numerator = np.sum(abs_diff)
    denominator = np.sum(od_matrix + od_transpose)
    
    return numerator / denominator

In [5]:
si_value_r5 = calculate_si_from_dataframe(r5TTM)
si_value_here = calculate_si_from_dataframe(hereTTM)
si_value_osrm = calculate_si_from_dataframe(osrm_TTM)
si_value_val = calculate_si_from_dataframe(val_TTM)
print(f"Symmetry Index: {si_value_r5:.4f} for r5")
print(f"Symmetry Index: {si_value_here:.4f} for here")
print(f"Symmetry Index: {si_value_osrm:.4f} for osrm")
print(f"Symmetry Index: {si_value_val:.4f} for Valhalla")

Symmetry Index: 0.0207 for r5
Symmetry Index: 0.0442 for here
Symmetry Index: 0.0096 for osrm
Symmetry Index: 0.0156 for Valhalla

$$
\text{Relative Difference R5} = \left( \frac{\text{R5} - \text{HERE}}{\text{HERE}} \right) \times 100
$$

$$
\text{Relative Difference OSRM} = \left( \frac{\text{OSRM} - \text{HERE}}{\text{HERE}} \right) \times 100
$$